name: kelp-o-matic
channels:
  - pytorch
  - conda-forge
dependencies:
  - python~=3.8,<=3.11
  - conda-forge::typer~=0.7.0
  - conda-forge::numpy~=1.24.2
  - conda-forge::rasterio~=1.3.6
  - conda-forge::tqdm~=4.65.0
  - pytorch::pytorch~=2.0.0
  - pytorch::torchvision~=0.15.0