name: hakai-segmentation
channels:
  - pytorch
  - conda-forge
dependencies:
  - python~=3.7,<3.10
  - conda-forge::typer~=0.4.1
  - conda-forge::numpy~=1.16
  - conda-forge::rasterio~=1.2
  - conda-forge::tqdm~=4.62
  - pytorch::pytorch~=1.10
  - pytorch::torchvision~=0.11
