name: Build Conda Package

on:
  workflow_call:
    input:
      python-version:
        type: string
        required: true
        description: Python version to build against

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ inputs.python-version }}
          auto-update-conda: true
          activate-environment: my-env
      - name: Install build packages
        run: |
          conda install -y anaconda-client conda-build conda-verify
      - name: Build package
        run: |
          cd conda
          conda build -c pytorch -c conda-forge --output-folder . .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: py${{ inputs.python-version }}-build
          path: noarch/*.tar.bz2
          if-no-files-found: error
#      - name: Upload packages
#        env:
#          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
#        run: |
#          anaconda upload --label main noarch/*.tar.bz2
